Models/Expert.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Apps.Models
{
    public class Expert
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public ICollection<ApplicationUserExpert> ApplicationUserExperts { get; set; }
        public ICollection<ApplicationUserExpertChangeRequestExpert> ApplicationUserExpertChangeRequestExperts{ get; set; }
        public ICollection<ActExpert> ActExperts { get; set; }
    }
}

Controllers/ExpertController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Apps.Data;
using Apps.Models;
using System.Web;
using Microsoft.AspNetCore.Identity;
using Apps.Services;
using Apps.Services.Downloaders;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace Apps.Controllers
{
    [Authorize(Policy = "IsExpert")]
    public class ExpertController : Controller
    {
        private ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;

        public ExpertController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Expert
        public async Task<IActionResult> Index()
        {
            ApplicationUser user = await _context.Users.Include(c => c.ApplicationUserExperts).Where(u => u.Email == User.Identity.Name).FirstOrDefaultAsync();
            ICollection<Expert> experts = await _context.ApplicationUserExperts.Include(aue => aue.ApplicationUser).Include(aue => aue.Expert).Where(aue => aue.ApplicationUserId == user.Id).Select(aue => aue.Expert).ToListAsync();
            List<Act> expertActs = new List<Act>();

            foreach(Expert expert in experts)
            {
                var acts = await _context.ActExperts.Include(ae => ae.Act).Include(ae => ae.Expert).Where(ae => ae.ExpertId == expert.Id).Select(ae => ae.Act).ToListAsync();
                
                if(null != acts)
                {
                    expertActs.AddRange(acts);
                }
            }

            ViewBag.User = user;
            ViewBag.UserExperts = experts;
            return View(expertActs);
        }


    }
}

Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Apps.Data;
using Apps.Models;
using System.Web;
using Microsoft.AspNetCore.Identity;
using Apps.Services;
using Apps.Services.Downloaders;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace Apps.Controllers
{
    [Authorize(Policy = "IsAdmin")]
    public class RequestsController : Controller
    {
        private ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;
        private RoleManager<IdentityRole> _roleManager;

        public RequestsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        // GET: Request
        public async Task<ActionResult> Index()
        {
            ViewBag.UserDataChangeRequests  = await _context.ApplicationUserDataChangeRequests.Include(r => r.ApplicationUser).ToListAsync();
            ViewBag.ExpertChangeRequests = await _context.ApplicationUserExpertChangeRequests.Include(r => r.ApplicationUser).ToListAsync();

            return View();
        }

        // GET: Requests/UserData/{id}
        public async Task<ActionResult> UserData(int? id)
        {
            ApplicationUserDataChangeRequest request = await _context.ApplicationUserDataChangeRequests.Include(r => r.ApplicationUser).Where(r => r.Id == id).FirstOrDefaultAsync();

            return View(request);
        }

        // POST: Requests/UserData/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> UserData(ApplicationUserDataChangeRequest request)
        {
            ApplicationUser user = await _context.Users.Where(u => u.Id == Request.Form["UserId"].ToString()).FirstOrDefaultAsync();

            user.FirstName = Request.Form["FirstName"].ToString();
            user.Surname = Request.Form["Surname"].ToString();
            user.MiddleName = Request.Form["MiddleName"].ToString();
            user.PhoneNumber = Request.Form["PhoneNumber"].ToString();

            _context.ApplicationUserDataChangeRequests.Remove(request);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // GET: Requests/Expert/{id}
        public async Task<ActionResult> Expert(int? id)
        {
            ApplicationUserExpertChangeRequest request = await _context.ApplicationUserExpertChangeRequests.
                Include(r => r.ApplicationUser).Include(r => r.ApplicationUserExpertChangeRequestExperts).Where(r => r.id == id).FirstOrDefaultAsync();

            //var requestData = await _context.ApplicationUserExpertChangeRequestExperts.Include(r => r.ApplicationUserExpertChangeRequest)
            //    .Include(r => r.Expert).Where(u => u.ApplicationUserExpertChangeRequestId == request.id).ToListAsync();

            ViewBag.Experts = await _context.Experts.ToListAsync();

            return View(request);
        }

        // POST: Requests/Expert
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Expert(ApplicationUserExpertChangeRequest request)
        {
            ApplicationUser user = await _context.Users.Where(u => u.Id == Request.Form["UserId"].ToString()).Include(u => u.ApplicationUserExperts).FirstOrDefaultAsync();
            string[] experts = Request.Form["Expert[]"];
            ICollection<Expert> expertsDb = await _context.Experts.ToListAsync();
            ICollection<ApplicationUserExpert> userExpertsList = new List<ApplicationUserExpert>();

            foreach (string id in experts)
            {
                if(expertsDb.Any(e => e.Id.ToString() == id))
                {
                    userExpertsList.Add(new ApplicationUserExpert()
                    {
                        ApplicationUser = user,
                        Expert = expertsDb.FirstOrDefault(e => e.Id.ToString() == id)
                    });
                }
            }

            user.ApplicationUserExperts = userExpertsList;
            _context.ApplicationUserExpertChangeRequests.Remove(request);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Requests/Expert.cshtml
@using Microsoft.AspNetCore.Identity
@using Apps.Data
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@model Apps.Models.ApplicationUserExpertChangeRequest

@{
    ViewBag.Title = "";
}

<h4> Expert request for user: @Model.ApplicationUser.Id</h4>
<div class="container">
    <div class="row">
        <div class="col-sm">
            <h6>User data:</h6>
            <p>Name: @Model.ApplicationUser.FirstName</p>
            <p>Surname: @Model.ApplicationUser.Surname</p>
            <p>Middle name: @Model.ApplicationUser.MiddleName</p>
            <p>Email: @Model.ApplicationUser.Email</p>
            <p>Phone Number: @Model.ApplicationUser.PhoneNumber</p>
        </div>
        <div class="col-sm">
            <h6>Requested experts: </h6>
            <form class="col-sm" asp-action="Expert">
                <input type="hidden" name="UserId" value="@Model.ApplicationUser.Id" />
                @foreach (Expert expert in ViewBag.Experts)
                {
                    @if (Model.ApplicationUserExpertChangeRequestExperts.Any(e => e.ExpertId == expert.Id))
                    {
                        <p>@expert.Name - Requested</p>
                        <input class="form-control" name="Expert[]" type="checkbox" value="@expert.Id" checked />
                    }
                    else
                    {
                        <p>@expert.Name</p>
                        <input class="form-control" name="Expert[]" type="checkbox" value="@expert.Id" />
                    }
                }
                <div class="form-group">
                    <input type="submit" value="Zapisz" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

Views/Requests/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using Apps.Data
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewBag.Title = "";
}

<h1> User data change request </h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">User</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @if (null != ViewBag.UserDataChangeRequests)
        {
            @foreach (var request in ViewBag.UserDataChangeRequests)
            {
                <tr>
                    <td>
                        @request.Id
                    </td>
                    <td>
                        @request.ApplicationUser.Id
                    </td>
                    <td>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Requests" asp-action="UserData" asp-route-id="@request.Id">Resolve</a>
                    </td>
                </tr>
            }
        }
        else
        {
            <td colspan="3">There aren't any available requests.</td>
        }
    </tbody>
</table>

<hr/>

<h1> User expert status request </h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">User</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @if (null != ViewBag.ExpertChangeRequests)
        {
            @foreach (var request in ViewBag.ExpertChangeRequests)
            {
                <tr>
                    <td>
                        @request.id
                    </td>
                    <td>
                        @request.ApplicationUser.Id
                    </td>
                    <td>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Requests" asp-action="Expert" asp-route-id="@request.id">Resolve</a>
                    </td>
                </tr>
            }
        }
        else
        {
            <td colspan="3">There aren't any available requests.</td>
        }
        </tbody>
    </table>

Views/Requests/UserData.cshtml
@using Microsoft.AspNetCore.Identity
@using Apps.Data
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@model Apps.Models.ApplicationUserDataChangeRequest

@{
    ViewBag.Title = "";
}

<h4> Data change request for user: @Model.ApplicationUser.Id</h4>
<div class="container">
    <div class="row">
        <div class="col-sm">
            <h6>Previous data</h6>
            <p>Name: @Model.ApplicationUser.FirstName</p>
            <p>Surname: @Model.ApplicationUser.Surname</p>
            <p>Middle name: @Model.ApplicationUser.MiddleName</p>
            <p>Email: @Model.ApplicationUser.Email</p>
            <p>Phone Number: @Model.ApplicationUser.PhoneNumber</p>
        </div>
        <form class="col-sm" asp-action="UserData">
            <h6>New data</h6>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" name="UserId" value="@Model.ApplicationUser.Id"/>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MiddleName" class="control-label"></label>
                <input asp-for="MiddleName" class="form-control" />
                <span asp-validation-for="MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Zapisz" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>